name: Deploy Next.js via Git Pull

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Pull latest changes
  pull-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Latest Changes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /home/bellukstudio/projects/wedding-lukman.bellukstudio.my.id
            echo "📥 Pull latest changes..."
            # Debug current state
            echo "Current user: $(whoami)"
            echo "Directory owner: $(ls -la . | head -2)"
            echo "Git directory owner: $(ls -la .git/ | head -2)"

            # Add safe directory untuk Git
            git config --global --add safe.directory /home/bellukstudio/projects/wedding-lukman.bellukstudio.my.id
            git config --global --add safe.directory '*'

            # Fix ownership issues
            sudo chown -R $(whoami):$(whoami) . || true

            git pull origin main
